# Generated by Django 3.2.3 on 2021-06-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', max_length=300)),
                ('response', models.CharField(default='Sorry ! your Request Cannot be processed', max_length=1000)),
            ],
        ),
    ]
